import { RepositoryStore } from './repository-store.js';import { Components } from './components.js';import { MarkdownRenderer } from './markdown-renderer.js';import { Utils } from './utils.js';
export class EasyScriptApp{constructor(data){this.store=new RepositoryStore(data);this.state={text:'',section:'all',type:'all'};this.currentResource=null;this.currentContent='';this.el={};}
init(){this.cacheDom();this.renderStatic();this.bindEvents();this.render();}
cacheDom(){['metrics','sectionFilters','typeFilter','searchInput','repositoryRoot','resultStatus','activeFilterLabel','modal','modalTitle','modalMeta','previewViewer','rawContent','copyModalBtn','downloadModalBtn','closeModalBtn','toast'].forEach(id=>this.el[id]=document.getElementById(id));}
renderStatic(){this.el.metrics.innerHTML=Components.metrics(this.store.stats());this.el.sectionFilters.innerHTML=Components.sectionFilters(this.store.data.sections);this.store.getTypes().forEach(type=>{const o=document.createElement('option');o.value=type;o.textContent=type.charAt(0).toUpperCase()+type.slice(1);this.el.typeFilter.appendChild(o);});}
bindEvents(){this.el.searchInput.addEventListener('input',e=>{this.state.text=e.target.value;this.render();});this.el.typeFilter.addEventListener('change',e=>{this.state.type=e.target.value;this.render();});this.el.sectionFilters.addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;this.state.section=b.dataset.section;this.el.sectionFilters.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));this.render();});this.el.repositoryRoot.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(!a)return;const r=this.store.getById(a.dataset.id);if(!r)return;await this.handle(a.dataset.action,r);});this.el.closeModalBtn.addEventListener('click',()=>this.closeModal());this.el.modal.addEventListener('click',e=>{if(e.target===this.el.modal)this.closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.el.modal.classList.contains('open'))this.closeModal();});this.el.copyModalBtn.addEventListener('click',()=>this.currentContent&&this.copy(this.currentContent));this.el.downloadModalBtn.addEventListener('click',()=>this.currentResource&&Utils.downloadText(Utils.fileName(this.currentResource.virtualPath),this.currentContent));document.querySelector('.dialog-tabs').addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(!t)return;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));document.querySelectorAll('.viewer').forEach(x=>x.classList.remove('active'));document.getElementById(t.dataset.tab==='preview'?'previewViewer':'rawViewer').classList.add('active');});}
async handle(action,r){try{this.toast(`Cargando: ${Utils.fileName(r.virtualPath)}`);const content=await this.store.load(r);if(action==='open')this.openModal(r,content);if(action==='copy')await this.copy(content);if(action==='download'){Utils.downloadText(Utils.fileName(r.virtualPath),content);this.toast(`Descarga preparada: ${Utils.fileName(r.virtualPath)}`);}}catch(error){this.toast('No se pudo abrir el archivo. Ejecuta el proyecto con un servidor HTTP local.');console.error(error);}}
render(){const results=this.store.query(this.state);this.el.repositoryRoot.innerHTML=Components.repository(this.store.group(results));this.el.resultStatus.textContent=`${results.length} de ${this.store.resources.length} recurso(s)`;const sn=this.state.section==='all'?'Todas las secciones':(this.store.data.sections.find(s=>s.id===this.state.section)?.name||'Sección');this.el.activeFilterLabel.textContent=`${sn} · ${this.state.type==='all'?'todos los tipos':this.state.type}`;}
openModal(r,c){this.currentResource=r;this.currentContent=c;this.el.modalTitle.textContent=r.title;this.el.modalMeta.textContent=`${r.sectionName} / ${r.categoryName} · ${r.virtualPath}`;this.el.previewViewer.innerHTML=r.virtualPath.toLowerCase().endsWith('.md')?MarkdownRenderer.render(c):`<pre><code>${Utils.escapeHtml(c)}</code></pre>`;this.el.rawContent.value=c;this.el.modal.classList.add('open');document.body.style.overflow='hidden';this.el.closeModalBtn.focus();}
closeModal(){this.el.modal.classList.remove('open');document.body.style.overflow='';this.currentResource=null;this.currentContent='';}
async copy(t){try{await Utils.copyText(t);this.toast('Contenido copiado');}catch{this.toast('No se pudo copiar el contenido');}}
toast(m){this.el.toast.textContent=m;this.el.toast.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.el.toast.classList.remove('show'),2200);}}
